[build]
providers = ["python"]

[start]
cmd = "streamlit run app/app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"

[variables]
PYTHONPATH = "."
APP_VERSION = "1.15.15"
# Force cache clear - updated 2025-07-05
