[supabase]
url = "https://hwnobuqvgmceqjjqmhkb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bm9idXF2Z21jZXFqanFtaGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDc3MzAsImV4cCI6MjA1OTQ4MzczMH0.ZB0pDLLx7z7DrQdnc64sSRCNn-KH2xWDdT44enbuFgs"

